### ISSUE TITLE
@MergeComponent strips @Component

### ISSUE THREAD

**Issue by kodebach** [r0adkll/kimchi#51]
Compiling this example

```kotlin
@Component
abstract class ParentComponent

object ChildScope

@MergeComponent(ChildScope::class)
abstract class ChildComponent(
    @Component val parent: ParentComponent
)
```

produces

```kotlin
@Component
public abstract class MergedChildComponent(
  parent: ParentComponent,
) : ChildComponent(parent) {
  public companion object
}

public fun KClass<ChildComponent>.createChildComponent(parent: ParentComponent):
    MergedChildComponent = MergedChildComponent::class.create(parent)
```

This is breaks the parent child relationship, because `@Component` (and also `val`) are stripped from `parent: ParentComponent`.

**Comment by r0adkll** [comment]
Thanks for the report! I apparently misunderstood how kotlin-inject handles explicit parent components and inheritance. I missed this since I primarily used the `@ContributesSubcomponent` mechanism of the library to handle these relations. This was great to point out as it is something that `@MergeComponent` components should support. Thanks again!
